### PR TITLE
Add proper confirm dialogs for login errors.

### PR DESCRIPTION
**Pull request by skittles1**
Replace the windows forms error boxes with the always-on-top confirm popup dialog (with single OK button).

Addresses issue #48

### CODE REVIEW

**Comment by cyberjunk** [comment]
Is the single OK button triggering the Cancel event?

It's just that you named the handler:
> OnLoginErrorConfirmed(..)

But registered it for the Cancel events.

**Comment by skittles1** [comment]
I should probably name it OnLoginErrorDialogClosed to reflect more closely what it does.

The OK button uses the same handlers as the No/Cancel button event.

**Comment by cyberjunk** [comment]
>> The OK button uses the same handlers as the No/Cancel button event.

I kinda feel like that "OK" should rather trigger the "Confirmed" event.
So for Yes/No you got both events and for "OK" only the "Confirmed".

**Comment by skittles1** [comment]
Changed the OK button to use the Confirmed event and adjusted the new login error dialogs to match (amended the commit).

**Pull request merged**
