### PR TITLE
Setting default keybindings to be in line with what people expect.

### PR DESCRIPTION
**Pull request by MorbusM59**
At least those that are familiar with other RPGs. That means that A and D are mapped as strafing left and right while rotating left and right has been sent to the left arrow and right keys. Opening doors is assigned to Space, since I haven't met a single person who had any sort of tolerance for it being default mapped to N. Sorry Shak :P 

This also includes a provisionary, but useful standard layout that should ring familiar with Meridian players. The hotkeys 1 to 0 and F1 to F12 are mapped as well as the hotkeys Q,E,R,F,T,G,B,N,Y,X,C,V as well as the ^key.

Obviously, there is a bit of an issue with different keyboard layouts. A few keys are based on the German keyboard layout, namely y for z and ^ for ~. I decided that the potential harm of having those keys bound anyway is fairly negligible and is outweighed by the benefit.

Additionaly, some windows have been made visible by default since they tend to be used frequently. (inventory, attributes, entities, spells and actions)

### CODE REVIEW

**Comment by skittles1** [comment]
I think having the default keybinding mirror classic is especially important for new players - the signs in Raza are based on the classic controls and when broadcasting for help with keys (mostly to open doors) the responses generally assume classic keybinding.

**Comment by cyberjunk** [comment]
To change the default binding, have a look here:
https://github.com/cyberjunk/meridian59-dotnet/blob/master/Meridian59.Ogre.Client/OISKeyBinding.cpp#L27

The configuration xml is basically only for visualiation purposes. It's not used anymore.
I haven't gone through all changes in detail, but there might be things I don't like :-p

**Comment by cyberjunk** [comment]
Oh, btw. please don't just make these windows all visible by default.
We discussed a nicer approach...

I added some notes how to save them with the configuration here:
https://github.com/cyberjunk/meridian59-dotnet/issues/150

**Comment by MorbusM59** [comment]
Ah yeah, right, sorry. I think my brain went poof at some point while trying to figure out how to get icons to display high resolution in the buff bar. :P Closing this crap pull then.

**Pull request closed without merging**
